### ISSUE TITLE
No path property on the route returned object

### ISSUE THREAD

**Issue by eokwukwe** [izzyjs/route#2]
Thank you for this helpful package.

Here are some issues I noticed when using it. 

1. The object returned from the `route` method does not have a `path` property.

    ```js
    const url = route('users.show', { id: '1' }) // /users/1
    
    url.method // GET
    url.pattern // /users/:id
    url.path // the path property does not exist
    ```

    And if you check the `Route` class declaration, there is no `path` property on the class.
    ```js
    export declare class Route extends String {
        readonly url: string;
        readonly method: Method;
        readonly params: string[] | undefined;
        readonly name: string;
        readonly pattern: string;
        readonly qs: URLSearchParams;
        private constructor();
        static replaceRouteParams(routePath: string, params: Record<string, string>): string;
        static new(routeName: unknown, params: unknown, qs?: unknown, prefix?: string): Route;
        static new(routeName: unknown): Route;
        static new(): Routes;
        static izzy(): {
            routes: SerializedRoute[];
            currentRoute: string;
        };
        toString(): string;
    }
    ```

2. `route('routename')` returns an instance of the `Route` class. When using it in `href` of `a` tag or the inertia `Link` there is no issue, but when using it in the inertia form helper to submit request for example:
    ```js
    form.post(route('signup.store'))
    ```
     it complains that `Argument of type 'Route' is not assignable to parameter of type 'string'` because the form helper expects a string. If the `path` property is available we could do `form.post(route('signup.store').path)` as a workaround.

**Comment by SH8GH** [comment]
i'm using like this

```tsx
  form.post(route('signup.store').toString())
```

**Note:** because `Route` class from what i see just extends from `StringConstructor`.

**Comment by ClementLaval** [comment]
Yep `path` does not exists,  it's `url` instead.
Could be cool to change the Readme or the lib.

**Comment by lncitador** [comment]
I correctly added the path property to the Route class in the latest release
